### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by J-D-Beltran** [jakowenko/phrame#2]
**Is your feature request related to a problem? Please describe.**
My feature request is to actually get in touch with you to hopefully collaborate on a new art project for exhibition in September! 

**Describe the solution you'd like**
I would love to discuss the variety of options in creating a standalone display, wall-mounted or standing on a shelf/table that would be an artwork constantly changing with your Phrame interface, but possibly a more limited image dataset and more conceptual parameters.

**Additional context**
I'm an artist/technologist who has shown my film/moving image artworks (that blend film/images with technology and interactivity) all over the world since 1998, my website is https://jdbeltran.com -- would love to learn how to translate some of my ideas and aesthetic into AI generated artworks.  My text contact is +1 415 786 6906.  My email contact is jdbeltran.studio@gmail.com, and I'm a professor at San Francisco State University in Design, at jdbeltran@sfsu.edu, https://design.sfsu.edu/people/jd-beltran -- I hope to hear from you soon, jakowenko! 🤞🏼

**Comment by jakowenko** [comment]
Hey @J-D-Beltran! Thanks for reaching out. I will follow up with you via email.
